// ============================================
// School Battle
// ContentFilter.js
// Content filtering for offensive language
// ============================================

// 禁止ワードリスト（差別用語、暴言、下ネタなど）
const BANNED_WORDS = [
    // 差別用語
    "ニガー", "nigger", "nigga", "negro",
    "イエローモンキー", "yellowmonkey", "yellow monkey",
    "ジャップ", "jap",
    "チンク", "chink",
    "ゴック", "gook",
    "外人", "gaijin",
    "土人", "dojin",
    "原住民",
    "野蛮人",
    "未開人",
    "劣等人種",
    "優生学",
    "民族浄化",
    "ホロコースト",
    "holocaust",
    
    // 暴言・脅迫
    "死ね", "shine",
    "殺す", "korosu", "kill",
    "殺すぞ",
    "消えろ", "kiero",
    "失せろ", "usero",
    "氏ね", "shine",
    "自殺", "jisatsu", "suicide",
    "自殺しろ",
    "死にたい",
    "お前ら死ね",
    "お前ら消えろ",
    "うざい", "uzai", "annoying",
    "うざいんだよ",
    "うっせぇ",
    "うっせえ",
    "キモい", "kimoii", "gross",
    "キモいんだよ",
    "気持ち悪い",
    "キショい",
    "キショいんだよ",
    "汚い", "kitanai",
    "デブ", "debu", "fat",
    "デブ野郎",
    "ブス", "busu", "ugly",
    "ブス野郎",
    "ブス女",
    "ブス男",
    "障害", "shougai",
    "障害者",
    "カス", "kasu", "trash",
    "カス野郎",
    "クズ", "kuzu", "scum",
    "クズ野郎",
    "ゴミ", "gomi", "garbage",
    "ゴミ野郎",
    "虫けら",
    "ムシケラ",
    "害虫",
    "害虫野郎",
    "豚野郎",
    "豚",
    "猿野郎",
    "猿",
    "犬野郎",
    "犬",
    "畜生",
    "チクショー",
    "チクショウ",
    "チッ",
    "糞", "kuso", "shit",
    "クソ", "kuso",
    "クソ野郎",
    "ファック", "fuck",
    "ファッキング", "fucking",
    "アホ", "aho",
    "アホ野郎",
    "バカ", "baka",
    "バカ野郎",
    "馬鹿",
    "馬鹿野郎",
    "阿呆",
    "阿呆野郎",
    "タコ", "tako",
    "タコ野郎",
    "ヘイタイ",
    "ヘイタイ野郎",
    "デタラメ",
    "適当",
    "適当野郎",
    "無能",
    "無能野郎",
    "能なし",
    "能なしだよ",
    "役立たず",
    "役立たず野郎",
    "無駄飯食らい",
    "無駄飯食い",
    "社会的に死ぬ",
    "社会的死刑",
    "炎上",
    "炎上しろ",
    "晒し上げ",
    "晒し",
    "人権",
    "人権ない",
    "人権なし",
    "人権侵害",
    "誹謗中傷",
    "中傷",
    "脅迫",
    "ストーカー", "stalker",
    "ストーカー野郎",
    
    // 下ネタ・性的表現
    "ちんこ", "chinko",
    "ちんちん", "chinchin",
    "ちんぽ", "chinpo",
    "ペニス", "penis",
    "penis",
    "まんこ", "manko",
    "マンコ",
    "おまんこ", "omanko",
    "膣", "chitsu",
    "性器",
    "性器野郎",
    "セックス", "sex",
    "sex",
    "エロ", "ero",
    "エロい",
    "エロ野郎",
    "ポルノ", "porno",
    "porn",
    "アダルト", "adult",
    "AV",
    "エロ動画",
    "ポルノ動画",
    "痴漢", "chikan",
    "痴漢野郎",
    "盗撮",
    "盗撮野郎",
    "レイプ", "rape",
    "強姦",
    "強姦野郎",
    "性的暴行",
    "セクハラ",
    "セクハラ野郎",
    "フェラ", "fera",
    "フェラチオ",
    "クンニ",
    "クンニリングス",
    "精液",
    "ザーメン",
    "射精",
    "オナニー", "onani",
    "オナニー野郎",
    "自慰",
    "自慰行為",
    "手淫",
    "指淫",
    "交尾",
    "性交",
    "コンドーム",
    "避妊",
    "中出し",
    "孕ませ",
    "孕む",
    "妊娠",
    "堕胎",
    "中絶",
    "売春",
    "売春婦",
    "ソープ",
    "風俗",
    "デリヘル",
    "ヘルス",
    "イメクラ",
    "性感マッサージ",
    "痴漢",
    "モーション",
    "本番",
    "生",
    "生姦",
    "無修正",
    "無修正野郎",
    "裏",
    "裏ビデオ",
    "裏画像",
    "エロ画像",
    "エロビデオ",
    "エロ漫画",
    "エロ小説",
    "官能小説",
    "ポルノ雑誌",
    "エロ雑誌",
    "ヌード",
    "全裸",
    "裸",
    "裸体",
    "脱衣",
    "脱衣野郎",
    "下着",
    "下着泥棒",
    "ブラ",
    "ブラジャー",
    "パンティ",
    "パンツ",
    "ショーツ",
    "ブラパン",
    "ランジェリー",
    "水着",
    "ビキニ",
    "微乳",
    "貧乳",
    "爆乳",
    "巨乳",
    "おっぱい", "oppai",
    "胸",
    "お尻", "oshiri",
    "尻",
    "ケツ",
    "アナル",
    "肛門",
    "尻穴",
    "ケツ穴",
    "アナルセックス",
    "尻フェチ",
    "スカトロ",
    "スカトロジー",
    "排泄",
    "排泄物",
    "糞便",
    "尿",
    "小便",
    "大便",
    "おしっこ",
    "うんち",
    "便所",
    "トイレ",
    "便所野郎",
    "トイレ野郎",
    "小便野郎",
    "大便野郎",
    
    // その他不快な言葉
    "テロ", "terror",
    "テロリスト", "terrorist",
    "爆弾",
    "爆撃",
    "殺戮",
    "虐殺",
    "大量殺人",
    "連続殺人",
    "殺人鬼",
    "狂人",
    "精神病",
    "精神異常",
    "頭おかしい",
    "頭悪い",
    "頭大丈夫",
    "頭壊れてる",
    "脳みそ",
    "脳みそない",
    "脳みそ腐ってる",
    "脳みそ大丈夫",
    "知的障害",
    "知的障害者",
    "精神障害",
    "精神障害者",
    "発達障害",
    "発達障害者",
    "自閉症",
    "自閉症野郎",
    "アスペルガー",
    "ADHD",
    "障害を持つ",
    "障害児",
    "障害児野郎",
    "身体障害",
    "身体障害者",
    "身体障害者野郎",
    "車椅子",
    "車椅子野郎",
    "盲人",
    "盲人野郎",
    "聾者",
    "聾者野郎",
    "唖者",
    "唖者野郎",
    
    // 英語の不快な言葉
    "bitch",
    "bastard",
    "asshole",
    "dick",
    "pussy",
    "cunt",
    "whore",
    "slut",
    "faggot",
    "retard",
    "idiot",
    "stupid",
    "dumb",
    "moron",
    "imbecile",
    "loser",
    "hater",
    "troll",
    "douche",
    "douchebag",
    "jackass",
    "dumbass",
    "shithead",
    "dickhead",
    "prick",
    "cock",
    "cock sucker",
    "motherfucker",
    "son of a bitch",
    "wanker",
    "twat",
    "arse",
    "arsehole",
    "bullshit",
    "crap",
    "damn",
    "hell",
    "suck",
    "sucks",
    "blowjob",
    "blow job",
    "handjob",
    "hand job",
    "boobs",
    "tits",
    "titties",
    "ass",
    "butt",
    "butthole",
    "rape",
    "molest",
    "molester",
    "pedophile",
    "necrophilia",
    "bestiality",
    "incest",
    "orgy",
    "prostitute",
    "hooker",
    "stripper",
    "pimp",
    "drug",
    "drugs",
    "cocaine",
    "heroin",
    "meth",
    "marijuana",
    "weed",
    "lsd",
    "ecstasy",
    "overdose",
    "suicide",
    "murder",
    "kill",
    "die",
    "death",
    "dead",
    "torture",
    "abuse",
    "abusive",
    "violence",
    "violent",
    "hate",
    "hateful",
    "racist",
    "racism",
    "discrimination",
    "nazi",
    "hitler",
    "kkk",
    "isis",
    "al qaeda",
    "taliban"
];

/**
 * 名前が禁止ワードを含んでいるかチェック
 * @param {string} name - チェックする名前
 * @returns {object} - { valid: boolean, reason: string }
 */
function validateName(name) {
    if (!name || typeof name !== 'string') {
        return { valid: false, reason: '名前が無効です' };
    }

    const normalized = name.toLowerCase().trim();
    
    // 空文字チェック
    if (normalized.length === 0) {
        return { valid: false, reason: '名前を入力してください' };
    }

    // 長さチェック（長すぎる名前を禁止）
    if (normalized.length > 20) {
        return { valid: false, reason: '名前は20文字以内にしてください' };
    }

    // 禁止ワードチェック
    for (const bannedWord of BANNED_WORDS) {
        if (normalized.includes(bannedWord.toLowerCase())) {
            return { valid: false, reason: '不適切な言葉が含まれています' };
        }
    }

    // 禁止ワードの部分一致チェック（文字を分けて入力する回避策対策）
    // 例: "死ね" -> "し ね" や "s h i n e" などを検出
    const spacedName = normalized.replace(/\s+/g, '').replace(/[\s\u3000]/g, '');
    for (const bannedWord of BANNED_WORDS) {
        if (spacedName.includes(bannedWord.toLowerCase())) {
            return { valid: false, reason: '不適切な言葉が含まれています' };
        }
    }

    // 類似文字置換チェック（例: "死ね" -> "死†ね" などを検出）
    const similarReplaced = normalized
        .replace(/[†‡※]/g, '')
        .replace(/[0-9]/g, '')
        .replace(/[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]/g, '');
    
    for (const bannedWord of BANNED_WORDS) {
        if (similarReplaced.includes(bannedWord.toLowerCase())) {
            return { valid: false, reason: '不適切な言葉が含まれています' };
        }
    }

    return { valid: true, reason: '' };
}

/**
 * テキストが禁止ワードを含んでいるかチェック
 * @param {string} text - チェックするテキスト
 * @returns {object} - { valid: boolean, reason: string }
 */
function validateText(text) {
    return validateName(text);
}

module.exports = {
    validateName,
    validateText,
    BANNED_WORDS
};
